### ISSUE TITLE
Installation fails in Solus

### ISSUE THREAD

**Issue by Azizb750** [aferrero2707/gimp-appimage#50]
Hi I tried to install gimp 2.99.1 but but the installation fails due of babl error(?)
here is the whole log
`DIR: /tmp/.mount_GIMP_ADrljU9
AILIBDIR=/tmp/tmp.HkHx9rfZ6d
deleting /tmp/tmp.HkHx9rfZ6d/libxcb-dri3.so*
System stdc++ library: "/usr/lib/libstdc++.so.6"
System stdc++ library version: "3.4.28"
Bundled stdc++ library version: "3.4.22"
Newest stdc++ library version: "3.4.28"
Using system stdc++ library
atomiclib: /usr/lib/libatomic.so.1
Checking versions of library "libfontconfig"
  system library: "/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  system library version: 1.11.1
  ailib: "/tmp/.mount_GIMP_ADrljU9/usr/lib/libfontconfig.so.1.11.1"
  bundled library: "/tmp/.mount_GIMP_ADrljU9/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  bundled library version: 1.11.1
  newest library version: "1.11.1"
Removing bundled "libfontconfig"
removed '/tmp/tmp.HkHx9rfZ6d/libfontconfig.so.1'
removed '/tmp/tmp.HkHx9rfZ6d/libfontconfig.so.1.11.1'
Checking versions of library "libfreetype"
  system library: "/usr/lib/libfreetype.so.6.14.0" (libfreetype.so.6.14.0)
  system library version: 6.14.0
  ailib: "/tmp/.mount_GIMP_ADrljU9/usr/lib/libfreetype.so.6.16.1"
  bundled library: "/tmp/.mount_GIMP_ADrljU9/usr/lib/libfreetype.so.6.16.1" (libfreetype.so.6.16.1)
  bundled library version: 6.16.1
  newest library version: "6.16.1"
GTK_PATH=/tmp/.mount_GIMP_ADrljU9/usr/lib/gtk-2.0
GTK_IM_MODULE_FILE=/tmp/.mount_GIMP_ADrljU9/usr/lib/gtk-2.0:/tmp/.mount_GIMP_ADrljU9/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_GIMP_ADrljU9/usr/lib
BABL_PATH /tmp/.mount_GIMP_ADrljU9/usr/lib/babl-0.1
GEGL_PATH /tmp/.mount_GIMP_ADrljU9/usr/lib/gegl-0.4
python=/tmp/.mount_GIMP_ADrljU9/usr/bin/python3
python3=/tmp/.mount_GIMP_ADrljU9/usr/bin/python3
/tmp/.mount_GIMP_ADrljU9/usr/bin/python=/tmp/.mount_GIMP_ADrljU9/usr/bin/python3
:Python:E::py::python3:
GIMP3_PLUGINDIR: /tmp/tmp.HkHx9rfZ6d/gimp/2.99
/tmp/.mount_GIMP_ADrljU9/apprun-helper.sh: γραμμή 179: /tmp/.mount_GIMP_ADrljU9/startup_scripts/*.sh: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος
Input parameters: ""

Input File: 
	linux-vdso.so.1 (0x00007ffd9e1ec000)
	libgimpwidgets-3.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgimpwidgets-3.0.so.0 (0x00007f508d100000)
	libgtk-3.so.0 => /tmp/tmp.HkHx9rfZ6d/libgtk-3.so.0 (0x00007f508c7f8000)
	libgdk-3.so.0 => /tmp/tmp.HkHx9rfZ6d/libgdk-3.so.0 (0x00007f508c508000)
	libatk-1.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libatk-1.0.so.0 (0x00007f508c2e0000)
	libcairo-gobject.so.2 => /tmp/tmp.HkHx9rfZ6d/libcairo-gobject.so.2 (0x00007f508c0d0000)
	libgimpconfig-3.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgimpconfig-3.0.so.0 (0x00007f508beb0000)
	libgimpmath-3.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgimpmath-3.0.so.0 (0x00007f508bca8000)
	libgimpthumb-3.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgimpthumb-3.0.so.0 (0x00007f508ba98000)
	libgimpcolor-3.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgimpcolor-3.0.so.0 (0x00007f508b880000)
	libgimpmodule-3.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgimpmodule-3.0.so.0 (0x00007f508b678000)
	libgimpbase-3.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgimpbase-3.0.so.0 (0x00007f508b448000)
	libappstream-glib.so.8 => /tmp/tmp.HkHx9rfZ6d/libappstream-glib.so.8 (0x00007f508b1e8000)
	libgdk_pixbuf-2.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgdk_pixbuf-2.0.so.0 (0x00007f508afc0000)
	libpangocairo-1.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libpangocairo-1.0.so.0 (0x00007f508adb0000)
	libpangoft2-1.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libpangoft2-1.0.so.0 (0x00007f508ab98000)
	libpango-1.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libpango-1.0.so.0 (0x00007f508a950000)
	libcairo.so.2 => /tmp/tmp.HkHx9rfZ6d/libcairo.so.2 (0x00007f508a638000)
	libpixman-1.so.0 => /tmp/tmp.HkHx9rfZ6d/libpixman-1.so.0 (0x00007f508a388000)
	libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x00007f508a340000)
	libexpat.so.1 => /tmp/tmp.HkHx9rfZ6d/libexpat.so.1 (0x00007f508a110000)
	libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f508a100000)
	libfreetype.so.6 => /tmp/tmp.HkHx9rfZ6d/libfreetype.so.6 (0x00007f5089e58000)
	libharfbuzz.so.0 => /tmp/tmp.HkHx9rfZ6d/libharfbuzz.so.0 (0x00007f5089bb8000)
	libpng16.so.16 => /tmp/tmp.HkHx9rfZ6d/libpng16.so.16 (0x00007f5089980000)
	libxcb-shm.so.0 => /tmp/tmp.HkHx9rfZ6d/libxcb-shm.so.0 (0x00007f5089778000)
	libxcb.so.1 => /tmp/tmp.HkHx9rfZ6d/libxcb.so.1 (0x00007f5089550000)
	libxcb-render.so.0 => /tmp/tmp.HkHx9rfZ6d/libxcb-render.so.0 (0x00007f5089340000)
	libXrender.so.1 => /tmp/tmp.HkHx9rfZ6d/libXrender.so.1 (0x00007f5089130000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f5088fd0000)
	libXext.so.6 => /tmp/tmp.HkHx9rfZ6d/libXext.so.6 (0x00007f5088db8000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f5088da8000)
	libgegl-0.4.so.0 => /tmp/tmp.HkHx9rfZ6d/libgegl-0.4.so.0 (0x00007f5088ad0000)
	libgegl-npd-0.4.so => /tmp/tmp.HkHx9rfZ6d/libgegl-npd-0.4.so (0x00007f50888c8000)
	libjson-glib-1.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libjson-glib-1.0.so.0 (0x00007f50886a0000)
	libbabl-0.1.so.0 => /tmp/tmp.HkHx9rfZ6d/libbabl-0.1.so.0 (0x00007f50883b0000)
	libgio-2.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgio-2.0.so.0 (0x00007f5088000000)
	libgmodule-2.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgmodule-2.0.so.0 (0x00007f5087df8000)
	libselinux.so.1 => /tmp/tmp.HkHx9rfZ6d/libselinux.so.1 (0x00007f5087bd0000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f5087bb0000)
	libmount.so.1 => /tmp/tmp.HkHx9rfZ6d/libmount.so.1 (0x00007f5087968000)
	liblcms2.so.2 => /tmp/tmp.HkHx9rfZ6d/liblcms2.so.2 (0x00007f5087708000)
	libgexiv2.so.2 => /tmp/tmp.HkHx9rfZ6d/libgexiv2.so.2 (0x00007f50874e0000)
	libexiv2.so.26 => /tmp/tmp.HkHx9rfZ6d/libexiv2.so.26 (0x00007f5086ee8000)
	libarchive.so.13 => /tmp/tmp.HkHx9rfZ6d/libarchive.so.13 (0x00007f5086c28000)
	libcrypto.so.10 => /tmp/tmp.HkHx9rfZ6d/libcrypto.so.10 (0x00007f50867c0000)
	liblzma.so.5 => /tmp/tmp.HkHx9rfZ6d/liblzma.so.5 (0x00007f5086598000)
	libbz2.so.1 => /tmp/tmp.HkHx9rfZ6d/libbz2.so.1 (0x00007f5086388000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f5086368000)
	libxml2.so.2 => /tmp/tmp.HkHx9rfZ6d/libxml2.so.2 (0x00007f5085ff8000)
	libmypaint-1.3.so.0 => /tmp/tmp.HkHx9rfZ6d/libmypaint-1.3.so.0 (0x00007f5085de0000)
	libjson-c.so.2 => /tmp/tmp.HkHx9rfZ6d/libjson-c.so.2 (0x00007f5085bd0000)
	libgobject-2.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgobject-2.0.so.0 (0x00007f5085978000)
	libffi.so.6 => /tmp/tmp.HkHx9rfZ6d/libffi.so.6 (0x00007f5085770000)
	libglib-2.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libglib-2.0.so.0 (0x00007f5085458000)
	libpcre.so.1 => /tmp/tmp.HkHx9rfZ6d/libpcre.so.1 (0x00007f50851f0000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f50851c8000)
	libunwind.so.8 => /tmp/tmp.HkHx9rfZ6d/libunwind.so.8 (0x00007f5084fa8000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f5084e58000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f5084e50000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5084c60000)
	libXi.so.6 => /tmp/tmp.HkHx9rfZ6d/libXi.so.6 (0x00007f5084a50000)
	libXfixes.so.3 => /tmp/tmp.HkHx9rfZ6d/libXfixes.so.3 (0x00007f5084848000)
	libatk-bridge-2.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libatk-bridge-2.0.so.0 (0x00007f5084618000)
	libwayland-client.so.0 => /tmp/tmp.HkHx9rfZ6d/libwayland-client.so.0 (0x00007f5084408000)
	libepoxy.so.0 => /tmp/tmp.HkHx9rfZ6d/libepoxy.so.0 (0x00007f50840d8000)
	libXinerama.so.1 => /tmp/tmp.HkHx9rfZ6d/libXinerama.so.1 (0x00007f5083ed0000)
	libXrandr.so.2 => /tmp/tmp.HkHx9rfZ6d/libXrandr.so.2 (0x00007f5083cc0000)
	libXcursor.so.1 => /tmp/tmp.HkHx9rfZ6d/libXcursor.so.1 (0x00007f5083ab0000)
	libXcomposite.so.1 => /tmp/tmp.HkHx9rfZ6d/libXcomposite.so.1 (0x00007f50838a8000)
	libXdamage.so.1 => /tmp/tmp.HkHx9rfZ6d/libXdamage.so.1 (0x00007f50836a0000)
	libxkbcommon.so.0 => /tmp/tmp.HkHx9rfZ6d/libxkbcommon.so.0 (0x00007f5083460000)
	libwayland-cursor.so.0 => /tmp/tmp.HkHx9rfZ6d/libwayland-cursor.so.0 (0x00007f5083258000)
	libwayland-egl.so.1 => /tmp/tmp.HkHx9rfZ6d/libwayland-egl.so.1 (0x00007f5083050000)
	libgcab-1.0.so.0 => /tmp/tmp.HkHx9rfZ6d/libgcab-1.0.so.0 (0x00007f5082e40000)
	libsoup-2.4.so.1 => /tmp/tmp.HkHx9rfZ6d/libsoup-2.4.so.1 (0x00007f5082b48000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f5082b28000)
	libpng15.so.15 => /tmp/tmp.HkHx9rfZ6d/libpng15.so.15 (0x00007f50828f8000)
	libthai.so.0 => /tmp/tmp.HkHx9rfZ6d/libthai.so.0 (0x00007f50826e8000)
	libfribidi.so.0 => /tmp/tmp.HkHx9rfZ6d/libfribidi.so.0 (0x00007f50824c8000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f508d390000)
	libgraphite2.so.3 => /tmp/tmp.HkHx9rfZ6d/libgraphite2.so.3 (0x00007f5082298000)
	libXau.so.6 => /tmp/tmp.HkHx9rfZ6d/libXau.so.6 (0x00007f5082090000)
	libblkid.so.1 => /tmp/tmp.HkHx9rfZ6d/libblkid.so.1 (0x00007f5081e50000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f5081c48000)
	libatspi.so.0 => /tmp/tmp.HkHx9rfZ6d/libatspi.so.0 (0x00007f5081a10000)
	libdbus-1.so.3 => /usr/lib/libdbus-1.so.3 (0x00007f50819c8000)
	libsqlite3.so.0 => /tmp/tmp.HkHx9rfZ6d/libsqlite3.so.0 (0x00007f5081710000)
	libgssapi_krb5.so.2 => /tmp/tmp.HkHx9rfZ6d/libgssapi_krb5.so.2 (0x00007f50814c0000)
	libsystemd.so.0 => /tmp/tmp.HkHx9rfZ6d/libsystemd.so.0 (0x00007f5081288000)
	libkrb5.so.3 => /tmp/tmp.HkHx9rfZ6d/libkrb5.so.3 (0x00007f5080f98000)
	libk5crypto.so.3 => /tmp/tmp.HkHx9rfZ6d/libk5crypto.so.3 (0x00007f5080d60000)
	libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007f5080d58000)
	libkrb5support.so.0 => /tmp/tmp.HkHx9rfZ6d/libkrb5support.so.0 (0x00007f5080b48000)
	libkeyutils.so.1 => /tmp/tmp.HkHx9rfZ6d/libkeyutils.so.1 (0x00007f5080940000)
	libcap.so.2 => /tmp/tmp.HkHx9rfZ6d/libcap.so.2 (0x00007f5080738000)
	liblz4.so.1 => /tmp/tmp.HkHx9rfZ6d/liblz4.so.1 (0x00007f5080520000)
	libgcrypt.so.11 => /tmp/tmp.HkHx9rfZ6d/libgcrypt.so.11 (0x00007f5080298000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f5080270000)
	libdw.so.1 => /tmp/tmp.HkHx9rfZ6d/libdw.so.1 (0x00007f5080018000)
	libattr.so.1 => /tmp/tmp.HkHx9rfZ6d/libattr.so.1 (0x00007f507fe10000)
	libelf.so.1 => /tmp/tmp.HkHx9rfZ6d/libelf.so.1 (0x00007f507fbf8000)

/tmp/.mount_GIMP_ADrljU9/usr/bin/gimp.bin --pdb-compat-mode=on ""
/tmp/.mount_GIMP_ADrljU9/usr/bin/python
DIRNAME: /tmp/.mount_GIMP_ADrljU9/usr/bin
DESKTOPFILE_NAME: gimp.desktop
APP_FULL: GNU Image Manipulation Program
APP: GNUImageManipulationProgram
APP_FULL: GNU Image Manipulation Program
APP: GNUImageManipulationProgram
BIN: /tmp/.mount_GIMP_ADrljU9/usr/bin/gimp.bin
DESKTOPINTEGRATION: 
../babl/babl-internal.h:214 babl_log()
	WARNING: the babl installation seems broken, no extensions found in queried
BABL_PATH (/tmp/.mount_GIMP_ADrljU9/usr/lib/babl-0.1) this means no SIMD/instructions/special case fast paths and
only slow reference conversions are available, applications might still
run but software relying on babl for conversions will be slow

../babl/babl-internal.h:222 babl_fatal()
	babl_format("CIE Lab double"): not found
sh: /tmp/babl.gdb: Άρνηση πρόσβασης

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.

warning: File "/usr/lib64/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".

warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
#3  0x00007f1107926f89 in babl_die () at ../babl/babl-internal.c:76
#4  0x00007f110791e1e5 in babl_fatal (format=format@entry=0x7f110794bbc3 "%s(\"%s\"): not found") at ../babl/babl-internal.h:224
#5  0x00007f110791f358 in babl_format (name=name@entry=0x95ad46 "CIE Lab double") at ../babl/babl-format.c:724
#6  0x000000000079370e in gimp_gradient_class_init (klass=<optimized out>) at gimpgradient.c:136
#7  gimp_gradient_class_intern_init (klass=<optimized out>) at gimpgradient.c:97
#8  0x00007f1104f0732e in type_class_init_Wm (pclass=0x30ca960, node=0x2f04820) at gtype.c:2232
#9  g_type_class_ref (type=<optimized out>) at gtype.c:2947
#10 0x00007f1104eed7b9 in object_set_property (nqueue=0x3034870, value=<optimized out>, pspec=0x351a250, object=0x34c8a20) at gobject.c:1447
#11 g_object_new_internal (class=class@entry=0x304e4f0, params=params@entry=0x7ffc8f1767d0, n_params=3) at gobject.c:1839
#12 0x00007f1104eef251 in g_object_new_valist (object_type=<optimized out>, first_property_name=first_property_name@entry=0x8c3d7b "children-type", var_args=var_args@entry=0x7ffc8f176918) at gobject.c:2128
#13 0x00007f1104eef58c in g_object_new (object_type=<optimized out>, first_property_name=first_property_name@entry=0x8c3d7b "children-type") at gobject.c:1648
#14 0x00000000007e3000 in gimp_list_new (children_type=49301536, unique_names=unique_names@entry=1) at gimplist.c:426
#15 0x00000000007796e7 in gimp_data_factory_constructed (object=0x2fd1150) at gimpdatafactory.c:203
#16 0x00007f1104eed442 in g_object_new_internal (class=class@entry=0x305dec0, params=params@entry=0x7ffc8f176cf0, n_params=7) at gobject.c:1845
#17 0x00007f1104eef251 in g_object_new_valist (object_type=<optimized out>, first_property_name=first_property_name@entry=0x93f9f6 "gimp", var_args=var_args@entry=0x7ffc8f176e38) at gobject.c:2128
#18 0x00007f1104eef58c in g_object_new (object_type=<optimized out>, first_property_name=first_property_name@entry=0x93f9f6 "gimp") at gobject.c:1648
#19 0x000000000077b736 in gimp_data_loader_factory_new (gimp=gimp@entry=0x31701a0, data_type=49301536, path_property_name=path_property_name@entry=0x959e3b "gradient-path", writable_property_name=writable_property_name@entry=0x8c1753 "gradient-path-writable", ext_property_name=ext_property_name@entry=0x94f1d0 "gradient-paths", new_func=0x793c80 <gimp_gradient_new>, get_standard_func=0x793d10 <gimp_gradient_get_standard>) at gimpdataloaderfactory.c:241
#20 0x000000000073cdc3 in gimp_data_factories_init (gimp=gimp@entry=0x31701a0) at gimp-data-factories.c:160
#21 0x0000000000739a6b in gimp_init (gimp=0x31701a0) at gimp.c:264
#22 0x00007f1104f09c0b in g_type_create_instance (type=<optimized out>) at gtype.c:1866
#23 0x00007f1104eed40d in g_object_new_internal (class=class@entry=0x307f2a0, params=params@entry=0x7ffc8f1772a0, n_params=2) at gobject.c:1805
#24 0x00007f1104eef251 in g_object_new_valist (object_type=<optimized out>, first_property_name=first_property_name@entry=0x929f11 "name", var_args=var_args@entry=0x7ffc8f1773e8) at gobject.c:2128
#25 0x00007f1104eef58c in g_object_new (object_type=<optimized out>, first_property_name=first_property_name@entry=0x929f11 "name") at gobject.c:1648
#26 0x000000000073a5b6 in gimp_new (name=name@entry=0x2dc7580 "/tmp/.mount_GIMP_ADrljU9/usr/bin/gimp.bin", session_name=session_name@entry=0x0, default_folder=default_folder@entry=0x0, be_verbose=be_verbose@entry=0, no_data=no_data@entry=0, no_fonts=no_fonts@entry=0, no_interface=0, use_shm=1, use_cpu_accel=1, console_messages=0, show_playground=1, show_debug_menu=1, stack_trace_mode=GIMP_STACK_TRACE_QUERY, pdb_compat_mode=GIMP_PDB_COMPAT_ON) at gimp.c:611
#27 0x00000000004ab830 in app_run (full_prog_name=0x2dc7580 "/tmp/.mount_GIMP_ADrljU9/usr/bin/gimp.bin", filenames=0x0, alternate_system_gimprc=alternate_system_gimprc@entry=0x0, alternate_gimprc=alternate_gimprc@entry=0x0, session_name=0x0, batch_interpreter=0x0, batch_commands=0x0, as_new=0, no_interface=0, no_data=0, no_fonts=0, no_splash=0, be_verbose=0, use_shm=1, use_cpu_accel=1, console_messages=0, use_debug_handler=0, show_playground=1, show_debug_menu=1, stack_trace_mode=GIMP_STACK_TRACE_QUERY, pdb_compat_mode=GIMP_PDB_COMPAT_ON, backtrace_file=0x2dc3a00 "/root/.config/GIMP-AppImage/2.99/CrashLog/GIMP-crash-1588531920.txt") at app.c:244
#28 0x00000000004aaf68 in main (argc=<optimized out>, argv=<optimized out>) at main.c:636
[Inferior 1 (process 34412) detached]
`
thanks

**Comment by Azizb750** [comment]
I close the thread cause there is already a similar issue
